services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    networks:
      - crypto_app_network
    ports:
      - "${BACKEND_API_PORT}:${BACKEND_API_PORT}"
    environment:
      - BINANCE_API_KEY
      - BINANCE_API_SECRET
    env_file:
    - .env

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile-dev
    networks:
      - crypto_app_network
    ports:
      - "${FRONTEND_API_PORT}:${FRONTEND_API_PORT}"
    env_file:
    - .env
networks:
  crypto_app_network:
